version: '3.3'

services:
  notification:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=${SENTRY_DSN}
      - QA_ENV=true
      - NODE_ENV=production

  countryconfig:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:${COUNTRY_CONFIG_VERSION}
    restart: unless-stopped
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - NODE_ENV=production
      - FHIR_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - APPLICATION_CONFIG_URL=http://config:2021
      - OPENHIM_URL=http://openhim-core:5001/fhir
      - CONFIRM_REGISTRATION_URL=http://openhim-core:5001/confirm/registration
      - CHECK_INVALID_TOKEN=true
      - MONGO_URL=mongodb://mongo1/user-mgnt?replicaSet=rs0
      - SENTRY_DSN=${SENTRY_DSN}
      - SENDER_EMAIL_ADDRESS=${SENDER_EMAIL_ADDRESS}
      - ALERT_EMAIL=${ALERT_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SECURE=${SMTP_SECURE}
    deploy:
      replicas: 1
    networks:
      - overlay_net

  client:
    environment:
      - DECLARED_DECLARATION_SEARCH_QUERY_COUNT=100

  gateway:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=${SENTRY_DSN}
      - COUNTRY=FAR
      - QA_ENV=true
      - NODE_ENV=production
      - NATIONAL_ID_OIDP_BASE_URL=${NATIONAL_ID_OIDP_BASE_URL}
      - NATIONAL_ID_OIDP_REST_URL=${NATIONAL_ID_OIDP_REST_URL}
      - NATIONAL_ID_OIDP_CLIENT_PRIVATE_KEY=${NATIONAL_ID_OIDP_CLIENT_PRIVATE_KEY}
      - NATIONAL_ID_OIDP_JWT_AUD_CLAIM=${NATIONAL_ID_OIDP_JWT_AUD_CLAIM}

  workflow:
    environment:
      - LANGUAGES=en,fr
      - SENTRY_DSN=${SENTRY_DSN}
      - QA_ENV=true
      - NODE_ENV=production

  search:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - QA_ENV=true
      - NODE_ENV=production

  metrics:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - QA_ENV=true
      - NODE_ENV=production

  auth:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - QA_ENV=true
      - NODE_ENV=production

  user-mgnt:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - QA_ENV=true
      - NODE_ENV=production
      - NATIONAL_ID_OIDP_BASE_URL=${NATIONAL_ID_OIDP_BASE_URL}
      - NATIONAL_ID_OIDP_CLIENT_ID=${NATIONAL_ID_OIDP_CLIENT_ID}
      - NATIONAL_ID_OIDP_ESSENTIAL_CLAIMS=${NATIONAL_ID_OIDP_ESSENTIAL_CLAIMS}
      - NATIONAL_ID_OIDP_VOLUNTARY_CLAIMS=${NATIONAL_ID_OIDP_VOLUNTARY_CLAIMS}

  webhooks:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - QA_ENV=true
      - NODE_ENV=production

  config:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - QA_ENV=true
      - NODE_ENV=production

  documents:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  scheduler:
    environment:
      - QA_ENV=true
      - NODE_ENV=production
